export const theme = {
  colors: {
    background: '#F7F4EE',
    surface: '#FFFFFF',
    surfaceMuted: '#EAE4DA',
    text: '#1F2933',
    textMuted: '#52606D',
    border: '#C9C2B7',
    primary: '#5B3A29',
    primaryText: '#FFFFFF',
    successBackground: '#E1F2E8',
    successText: '#205C3B',
    neutralBackground: '#ECEFF2',
    dangerBackground: '#FBE9E7',
    dangerText: '#8A2C24',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  radius: {
    sm: 8,
    md: 12,
  },
  typography: {
    caption: 14,
    metadata: 15,
    body: 16,
    itemTitle: 20,
    sectionTitle: 24,
    pageTitle: 32,
    bodyLineHeight: 24,
    overlineLetterSpacing: 0.5,
  },
  layout: {
    contentMaxWidth: 960,
    dialogMaxWidth: 560,
    cardMinHeight: 112,
    cardTextMinWidth: 200,
    paginationButtonMinWidth: 112,
  },
  borderWidth: 1,
  minTargetSize: 44,
} as const;
